version: '2.1'
services:
  besu-node-1:
    user: root
    container_name: besu-node-1
    volumes:
      - ../node/besu-1/data:/opt/besu/data
      - ../genesis:/opt/besu/genesis
    image: hyperledger/besu:24.1.2
    entrypoint:
      - /bin/bash
      - -c
      - besu --data-path=data --genesis-file=genesis/genesis.json --bootnodes=enode://4a65cc3f35aa84462bfa233e4ea8b990ca9bbb83a5f229fb30a40cc9c46176f3970c4d54fe445678016444b6394b400cc7a9760b63e89d7993a69a464175c553@172.29.0.2:30303 --p2p-port=30304 --rpc-http-enabled --rpc-http-api=ETH,NET,QBFT --host-allowlist="*" --rpc-http-cors-origins="all" --rpc-http-port=8546 --min-gas-price=0
    ports:
      - "8546:8546"
      - "30304:30304"
    networks:
      besu_network:
    restart: always
  besu-node-2:
    user: root
    container_name: besu-node-2
    volumes:
      - ../node/besu-2/data:/opt/besu/data
      - ../genesis:/opt/besu/genesis
    image: hyperledger/besu:24.1.2
    entrypoint:
      - /bin/bash
      - -c
      - besu --data-path=data --genesis-file=genesis/genesis.json --bootnodes=enode://4a65cc3f35aa84462bfa233e4ea8b990ca9bbb83a5f229fb30a40cc9c46176f3970c4d54fe445678016444b6394b400cc7a9760b63e89d7993a69a464175c553@172.29.0.2:30303 --p2p-port=30305 --rpc-http-enabled --rpc-http-api=ETH,NET,QBFT --host-allowlist="*" --rpc-http-cors-origins="all" --rpc-http-port=8547 --min-gas-price=0
    ports:
      - "8547:8547"
      - "30305:30305"
    networks:
      besu_network:
    restart: always

networks:
  besu_network:
    external: true